### ISSUE TITLE
Forestry bees are invisible in the GUI

### ISSUE THREAD

**Issue by GusSmedstad** [jrbudda/minecrift#316] opened 2018-08-18 14:35 UTC
Forestry’s bees are invisible in your inventory, though they show up in the world if you hold them or drop them. I strongly suspect this is the same bug as Railcraft’s locomotives being invisible in inventory - both items are colored in a two-pass process where the mod takes a grayscale icon and adds color. In Forestry’s case it’s because there are a very large number of bees differentiated only by color. In Railcraft, the player can re-color locomotives in a variety of combinations.

Both problems are Vivecraft specific, the items render correctly without Vivecraft.

I’m using the 1.7.10 Vivecraft client.

**Comment by Techjar** [comment] 2018-08-18 16:07
Known issue, never could figure it out. Also duplicate of #130.

**Closed as completed by Techjar** 2018-08-18 16:07 UTC
