### ISSUE TITLE
[Forge Mod] Black Starting Room in Lord of the Rings Mod

### ISSUE THREAD

**Issue by cherbert** [jrbudda/minecrift#41] opened 2016-06-05 11:31 UTC
I don't know how or why its any different from other mods but the Lord of the Rings Mod seems to cause a black screen starting area when you load into VR. You can't see the Minecraft menu screen. You can kind of see it off screen but wherever you look your view gets blocked by a b lack veil.

Anyway.. I know other things are probably more important but if you get a chance to have a look it would be very cool to play this mod in VR.

**Comment by fucnknown** [comment] 2016-06-05 17:48
Please check in the mods folder if you have one called "custommenu", or similar if so, remove it. Check the information in the wiki; (https://www.reddit.com/r/Vive/wiki/minecrift_for_vive)

**Comment by cherbert** [comment] 2016-06-05 18:17
It is the only mod I am running.

**Comment by fucnknown** [comment] 2016-06-05 19:41
Sorry, thought it was a mod pack; The problem is that it modifies the main menu, and that conflicts with the rendering. If you can get hold of the developer or the source and disable the menu, it'll work ok

**Comment by cherbert** [comment] 2016-06-05 22:00
The developer says he uses no custom menu. I have to admit when using outside of Vivecraft the menu looks pretty vanilla to me.

**Comment by MggMuggins** [comment] 2016-06-06 02:19
As far as I know, we don't use a custom menu (It's Samwise, from the wiki). However, Mevans has changed a lot of things to new formats which may be incompatible with this mod. It's possible the LOTR menu has trouble...
~SamwiseFIlmore

**Comment by jrbudda** [comment] 2016-06-06 02:38
Not really sure where to begin with this one... is the source for the mod available?

**Comment by jrbudda** [comment] 2016-06-06 02:51
It's not the menu, per se, there's.... something... being rendered as a GUI screen and it probably supposed to be transparent, but isn't due to alpha/blending changes I've made. And it renders right in your face and sort of tracks with the viewpoint.

**Comment by MggMuggins** [comment] 2016-06-06 03:16
Hmm. Technically the mod source is not available. However, it is possible to decompile the classes and view the code, albeit with obfuscated function names. Mevans is also technically alright with decompiling the mod source. However, unless it's completely necessary, try to avoid it. It's possible it has something to do with the map in the LOTR menu. Try disabling sepia. That sounds like what you're describing.
~Samwise

**Comment by Techjar** [comment] 2016-06-27 12:54
Does this still occur on the latest version?

**Comment by denny99** [comment] 2016-06-27 17:32
Now we've got a proper crash report right on launch

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 27.06.16 19:28
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:188)
    at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:258)
    at org.lwjgl.opengl.GL11.glMultMatrix(GL11.java:2341)
    at net.minecraft.client.renderer.EntityRenderer.renderGuiLayer(EntityRenderer.java:3965)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1781)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1533)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1311)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 197418160 bytes (188 MB) / 783532032 bytes (747 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total;-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 4 mods loaded, 4 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJA  FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHIJA  Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHIJA  lotr{Beta v28.2 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B28.2.jar) 
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda23r1-forge-nohydra
LWJGL: 2.9.1
OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 368.39
OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8
```

**Comment by jrbudda** [comment] 2016-06-27 17:39
..... whaaaaat.... is your headset plugged in? Could you pastebin the startup prior to that crash?

edit: never mind. reproducible here

**Comment by jrbudda** [comment] 2016-06-27 18:11
oooooooh we're on to something now, boys.

**Comment by jrbudda** [comment] 2016-06-27 19:26
Test this please I don't know how it's supposed to work.

[vivecraft-1.7.10-Vivecraft-jrbudda24-installer.zip](https://github.com/jrbudda/minecrift/files/335679/vivecraft-1.7.10-Vivecraft-jrbudda24-installer.zip)

**Comment by denny99** [comment] 2016-06-27 20:15
Will test it tomorrow. At least i am able to load the world. So seems good for now.

**Comment by denny99** [comment] 2016-06-28 13:04
Ok. Seems to work, but weapons are disorientated.
![lotrweapon](https://cloud.githubusercontent.com/assets/1826849/16416229/96643618-3d41-11e6-8fdb-2bb1c5168c03.png)

**Comment by Techjar** [comment] 2016-06-28 13:05
Yeah, that's the same thing as issue #101

**Comment by jrbudda** [comment] 2016-06-28 13:22
Woo. see sometimes you have to make things worse before you can make them better. I never would a guessed what was going before I made it crash doing something else. Gonna close this issue.

**Closed as completed by jrbudda** 2016-06-28 13:22 UTC
Labels: mod bug
