### ISSUE TITLE
[Suggestion] Ability to attach camera to a controller

### ISSUE THREAD

**Issue by Octillerysnacker** [jrbudda/minecrift#215] opened 2016-08-07 03:34 UTC
Basically what Valve did in their Vive trailer. I've yet to find any other mods that utilize Lighthouse.

If you guys were to add this, it would be great if you could bind the camera to any controller (so there's no third controller nonsense) and add offsets.  

And maybe add an undistorted mixed reality mirror? I'm trying to do edited augmented reality by using a custom resource pack for greenscreens, then recording whats on screen and attaching a GoPro to the Vive, though I'm not having a lot of luck.

**Comment by jrbudda** [comment] 2016-08-07 04:06
wait... how is what you're asking for different than how it works now? If the camera follows one of the 2 controllers, how will you use it?

**Comment by Octillerysnacker** [comment] 2016-08-07 04:13
Unless I'm missing something, the camera stays static, and it would be great to have a dynamic camera option (It's kind of like the hololens mine craft demo, but not realtime(or at least it doesn't have to be)). Honestly it's more of a way to utilize Lighthouse than it is to add to the whole VR experience. If I could make this myself I would but Java is confusing.

**Comment by jrbudda** [comment] 2016-08-07 04:34
you need both controllers to play the game tho, if you're using one for the camera you can't play correctly, right?

**Comment by Chimera245** [comment] 2016-08-07 11:47
Maybe he means for spectators/video recording? Like what shows up on the computer screen instead of inside the Vive headset?

**Comment by Octillerysnacker** [comment] 2016-08-07 15:18
That's exactly what I mean, and I don't even have to be playing Minecraft correctly, I could just act as  cameraman in spectator mode and with adjusted world scaling. It's a pain trying to do it just with the headset.

**Comment by hornygranny** [comment] 2016-09-29 04:24
@jrbudda a third controller can be attached with USB, and is also tracked by the lighthouses. the steamvr plugin in unity matches the in-game camera for mixed reality to that object in the engine, which moves that object according to the position of the third controller in the real world. no idea what is possible for you here, but it would make it much easier to do MR

**Comment by Aesop112** [comment] 2016-12-12 02:44
Damn that's cool. I'd also like a 3rd person spectator view for normal playing too for others watching.

**Comment by chrislennon** [comment] 2017-01-10 10:48
As someone starting to play with mixed reality filming, attaching the camera to the third controller (when available) would be a nice addition. 👍 

I tested briefly with MR view however I could not get the camera to move using the app menu + grip button, moving it manually did work. I may of experienced this due to having the 3rd controller plugged in (assuming support was there). I will do further testing tonight, if I can confirm it I will post the results in here and discord support channel.

**Comment by Techjar** [comment] 2017-01-10 13:50
We can't easily implement 3rd controller support without physical access to one, though if you want to work with us in the discord we could try.

**Comment by jrbudda** [comment] 2017-02-10 23:17
woo finally!

**Closed as completed by jrbudda** 2017-02-10 23:17 UTC
Labels: request, resolved
