### ISSUE TITLE
v21 teleporting into walls getting stuck

### ISSUE THREAD

**Issue by Valadon** [jrbudda/minecrift#120] opened 2016-06-24 05:14 UTC
After I installed v21 I noticed that I would seem to teleport into a wall or floor fairly often (this didn't happen at all in v20.) When I get stuck in a wall I see dirt on all sides of me,and it is relatively dark. Some times I am able to teleport out if I point in a random direction but sometimes I have to switch to free move and walk out that way. 

Take this with a grain of salt as I also upgraded my motherboard, cpu, and ram today in hopes that it would give me a smoother fps (it didn't, I guess my gtx 970 isn't up to snuff). But these issues could be related to the new hardware or the fresh install of windows/minecraft that I did today. I am also getting an odd sound glitch. All of the sounds are kind or garbled, possibly doubled? I would imagine it is related to the new OS install and not v21, but I just thought I would mention it.

**Comment by jrbudda** [comment] 2016-06-24 10:17
I can't imagine a hardware upgrade causing something like that. That being said I still can't reproduce your issue. Is this singleplayer, multiplayer, forge or no-forge?

**Comment by wildstyle007** [comment] 2016-06-25 13:57
This happened to me also with v22 -- I got stuck inside a single block wall. Had to walk out with room scale. Also fell down sometimes when teleporting up to ledges, which didn't happen on previous builds.

Not sure if this also relates to world scale and player bounds.

**Comment by masaokun2** [comment] 2016-06-25 16:52
I get this constantly in v21 (have not tried v22 yet).  It happens when I teleport onto the very edge of a block.  It also happens _much_ more often when I have the non-survival mode teleport option (so I can target the sides of blocks).  It teleports to the edge and then falls, often ending up with a stopping point under the floor, which puts your head inside the wall you were teleporting to, so you can't see anything.  My janky workaround is that if I lean forward as I teleport, it tends to happen less often.

**Comment by jrbudda** [comment] 2016-06-25 19:17
Does messing with the 'walk up blocks' locomotion change the behavior at all?

**Comment by masaokun2** [comment] 2016-06-26 06:07
No luck, unfortunately.

**Comment by jrbudda** [comment] 2016-06-26 13:45
should be fixed in v23, could you test?

**Comment by masaokun2** [comment] 2016-06-26 16:00
Absolutely!

**Comment by masaokun2** [comment] 2016-06-26 17:42
Played over 30 minutes with no problems.  Looks fixed to me!  Thank you so
much for everything!  Best of luck with 1.10!!

Michael / Masao-Kun
On Jun 26, 2016 11:00 AM, "Michael O'Keefe" masaokun@gmail.com wrote:

Absolutely!

**Comment by jrbudda** [comment] 2016-06-26 17:42
great and thanks.

**Closed as completed by jrbudda** 2016-06-26 17:42 UTC
Labels: bug, resolved
