### ISSUE TITLE
Right pad appears to be hardcoded AND reconfigable in inventories

### ISSUE THREAD

**Issue by Nixill** [jrbudda/minecrift#199] opened 2016-07-27 04:50 UTC
_Forge installation [with mods](https://gist.github.com/NixillUmbreon/de1337e66801063f2a95ed6442244e73), singleplayer creative, v29r1 in 1.7.10_

_This issue may be reproducible *_without*\* mods via the instructions at the bottom of this post.*

Due to the fact that I now have mods, I decided to add buttons for them to my controllers. To be specific, left pad top right got key-hold(B), right pad got key-hold(-), and left pad got key-hold(+). Within NEI itself I then bound recipe, enchantments, and potion creator to those buttons.

The left-top-right button is working properly, but the two right-bottom buttons are acting strange: The game will perform a right-click before executing the keypress. This means if I'm hovering over an item it will be half picked up, then the enchantments screen will open (which Minecraft sees as closing an inventory, forcing the item to drop into the world, then opening a new one).

This isn't purely a mod issue as reaching over to my real keyboard and pressing minus works fine.

---

I've yet to test this myself but here's a way to test it without mods:

The instructions were removed because they don't work.

**Comment by jrbudda** [comment] 2016-07-30 07:50
duplicate of #183. will work on this soon.

**Closed as completed by jrbudda** 2016-07-30 07:50 UTC
