### ISSUE TITLE
stuttering issues

### ISSUE THREAD

**Issue by OscarHalse** [jrbudda/minecrift#99] opened 2016-06-16 14:09 UTC
Love your work, but unfortunately it stutters pretty badly.

My specs are a FX-8350 and a 970, so my GPU and CPU both hover around 30-40% utilization while in game. I have tried upping and downing nearly every settings and so far this has been my findings:
- Turning the chunk loading down actually INCREASE stutter for some very strange reason, I speculate that this might have been due to it pushing the textures in and out of VRAM, and the chunks in and out of RAM, however it persists even after having stod completely still for exstended periods of time. 
- There seems to be no difference at all in stutter when using 2x AA in the VR settings, however doing 3X increases the stutter.
- The steam VR overlay works just fine, but going into desktop mode through the HMD makes it stutter crazy bad, like 15FPS bad...
- Rain seems to make it stutter worse
- Rain also renders strangely, where in around 50% of the particles bellow 40 degrees of your vertical FOV while looking ahead renders statically to the HMD and moves around as you move your head. The particles rendered higher up (i.e looking upwards) moves and acts like they are supposed to. 
- Having OBS recording the screen seems to make the stutter worse, however it is very slight.

Updates:
- Here is the GPU diagnostics while I open and close the desktop mode in the steam overlay: https://i.imgur.com/IBc3yHJ.png
  
  The two spikes are when I open steam VR desktop overview, the lower parts are when I am within vivecraft itself. The first one the HMD was laying fairly still, so you see it is a bit more spikey, however on the second one I was constantly moving it around, which as you can see caused more continuous strain on the GPU.
- The chunk rendering distance discrepency seems to have seized. I mainly test in V20, and now while lowering and increasing the chunk render distance anything below 4 and above 12 increase the stutter. Anything in between seems to be pretty on par.

**Comment by kuar-z** [comment] 2016-06-16 14:18
Possible duplicate of #80, same CPU FX-8350.

**Comment by OscarHalse** [comment] 2016-06-16 15:22
That was my first thought as well, however it doesn't seem to change the load on the CPU, and concidering the oddities accouring on the GPU, it would be strange for it to be the CPU's fault.

**Comment by jrbudda** [comment] 2016-06-23 17:25
Closing this as there is really nothing else I can do. Minecraft is just poorly coded and a cpu hog.

**Closed as completed by jrbudda** 2016-06-23 17:25 UTC
