### ISSUE TITLE
[Mod Bug] 3D rendered items hover in hand

### ISSUE THREAD

**Issue by zeshinumi** [jrbudda/minecrift#153] opened 2016-06-28 11:52 UTC
Any rendered item, such as pokeballs from pixelmon, swords from DBC, or the wands from Thuamcraft, seem to float above your hand at a weird angel. I don't know if this is something mod devs would have to compensate for, or if it could be fixed by vive craft, but it makes it a little awkward. I'll get screen shots later if needed.

**Comment by Techjar** [comment] 2016-06-28 12:03
Caused by our mess ItemRenderer. Basically duplicate of #101

**Closed as completed by Techjar** 2016-06-28 12:03 UTC
Labels: duplicate
