### ISSUE TITLE
"Malformed class name" crash on world load.

### ISSUE THREAD

**Issue by proxio-david** [jrbudda/minecrift#187] opened 2016-07-11 16:23 UTC
After upgrading to v27, Minecraft crashes every time I try to load my world. Rolling back to v26 solves the problem, and re-installing v27 brings it back.

I'm running single player without any other mods.

[crash-2016-07-11_18.15.00-client.txt](https://github.com/jrbudda/minecrift/files/357543/crash-2016-07-11_18.15.00-client.txt)

**Comment by Techjar** [comment] 2016-07-11 16:24
Do a clean re-install of Minecraft, this is the only way we currently know of to fix this problem.

**Comment by Techjar** [comment] 2016-07-11 16:27
Also duplicate of #181 and #185, so putting that here for reference.

**Comment by Techjar** [comment] 2016-07-11 16:29
I'm going to keep this one open so we can have a reference and note to try to find whatever the hell is causing this.

**Comment by jrbudda** [comment] 2016-07-12 00:36
It's tied to a file called usercache.json that is used by the integrated server to do ... something. I don't even have that file on my installation and can't figure out how to generate it. Maybe it's something that works when you Open to LAN?

The game handles the file being missing no problem but I don't know whats up with 'malformed class name'. I guess we need to get a copy of someone's usercache.json who is experiencing the crash.

The whole thing is tied to mojang's authlib.. maybe we changed the dependency version or something.

**Comment by dav-eli** [comment] 2016-07-12 05:10
Sorry, forgot to check to check if there were any closed bugs for this problem,

Here is my [usercache.json.txt](https://github.com/jrbudda/minecrift/files/358582/usercache.json.txt)

Deleting usercache.json solves the problem.

**Comment by Techjar** [comment] 2016-07-12 05:11
Uh... there's absolutely nothing weird about that file. It looks exactly like it's supposed to. I'm really confused now...

**Comment by dav-eli** [comment] 2016-07-12 05:15
Let me know if there's anything else I can do to help.

**Comment by mother9987** [comment] 2016-07-12 16:01
I kept my .minecraft folder that didn't work also.  If there are any files in there that'd help, I'm happy to send.

**Comment by swordboy98** [comment] 2016-07-13 01:12
I am also getting this error. It started with V27, but still is present with V28. I uninstalled Minecraft and removed the minecraft appdata folder before re-installing.  This didn't seem to make a difference. I can also provide any requested files.

**Comment by Joeness** [comment] 2016-07-13 15:50
I just got my vive yesterday, and tried to get Vivecraft working today, I too am instant crashing on first attempt to create a world with "Malformed Class Name"
[crash-2016-07-13_08.43.01-client.txt](https://github.com/jrbudda/minecrift/files/361858/crash-2016-07-13_08.43.01-client.txt)
, no other mods installed. minecraft was just installed about 20min before so its as fresh and new as can be.

**Comment by jrbudda** [comment] 2016-07-13 18:32
OKAY. usercache.json is generated when you load world in 1.10. Now that I know where it comes from maybe I can fix it. Deleting usercache.json should still fix your crash in vivecraft until then.

**Comment by Techjar** [comment] 2016-07-13 19:29
What? My 1.7.10 modded instance (totally separate game directory, never ran 1.10 on it) has a usercache.json and does not experience this issue. I've also run 1.10 on my normal game directory and it works fine too, so I don't see how it could possibly be caused by that file. Additionally, for several people deleting the usercache.json did not fix the problem, only deleting the entire directory did.

**Comment by jrbudda** [comment] 2016-07-13 19:43
Fixed I think.

[vivecraft-1.7.10-Vivecraft-jrbudda28-installer.exe.zip](https://github.com/jrbudda/minecrift/files/362319/vivecraft-1.7.10-Vivecraft-jrbudda28-installer.exe.zip)

**Comment by Joeness** [comment] 2016-07-13 20:07
It works! and HOLY CRAP IM INSIDE MINECRAFT (I love you)

**Comment by dav-eli** [comment] 2016-07-14 05:34
Works for me to!

**Closed as completed** 2016-07-28 02:20 UTC
Labels: bug, resolved
