### ISSUE TITLE
Newest update causes vertical movement to be reversed at 1.00 scale.

### ISSUE THREAD

**Issue by Octavian-the-ent** [jrbudda/minecrift#124] opened 2016-06-25 02:51 UTC
At the normal scale, ducking down now causes my viewpoint to go up the corresponding distance, and vice versa. This only seems to happen while at normal scale as well.

**Comment by kuar-z** [comment] 2016-06-25 03:49
Perform a clean install to a new folder and report back.

**Comment by jrbudda** [comment] 2016-06-25 04:07
That's weird, do you have 'allow crawling' on or off?

**Comment by Octavian-the-ent** [comment] 2016-06-25 05:30
Allow crawling is on.

**Comment by jrbudda** [comment] 2016-06-25 05:49
Does that affect the behavior you are seeing?

**Comment by Dung3onlord** [comment] 2016-06-25 09:50
I am also having the same issue. It seems like the world is moving on the y axes instead of your head only.
If that might be helpful it doesn't happen in the home screen

**Comment by wildstyle007** [comment] 2016-06-25 14:02
Confirming i was seeing a similar behavior when looking out doors / windows up-close

**Comment by jrbudda** [comment] 2016-06-25 14:05
Do any of the locomotion options change the behavior? does being in free-move or teleport mode make a difference? Single-player, multiplayer or both?

**Comment by wildstyle007** [comment] 2016-06-25 14:57
Some more info:
- I deleted the forge version and tested on vanilla, it worked great!!
- Then deleted the vanilla profile and reinstalled the forge version, the problem came back.

So, only affecting forge version for me at least.

**Comment by jrbudda** [comment] 2016-06-25 15:34
Single player or multiplayer or both?. Any mods in that forge install? Do any of the locomotion options change the behavior? I ask these because I cannot reproduce your problem and If I can't reproduce it I can't fix it. Thanks.

**Comment by wildstyle007** [comment] 2016-06-25 16:33
>  Do any of the locomotion options change the behavior?

Yes - If I turn "Allow crawling" OFF then the problem stops.

**Comment by Octavian-the-ent** [comment] 2016-06-25 16:40
I can't do any testing right now, but when I filed the issue last night I tested it on both a modded forge install, and a vanilla forge install, and the issue was in both. Only tested on single player and in free move mode. It worked fine in the main menu and when the in game menu was opened. I will investigate the issue further later today.

**Comment by Octavian-the-ent** [comment] 2016-06-25 18:56
I can also confirm that turning off "allow crawling" seems to resolve this issue.

**Comment by jrbudda** [comment] 2016-06-25 19:14
Yea... but only with forge... what on earth.

**Comment by jrbudda** [comment] 2016-06-26 13:45
should be fixed in v23

**Closed as completed** 2016-06-27 02:57 UTC
