### ISSUE TITLE
Character skin missing after updating to Vivecraft 27

### ISSUE THREAD

**Issue by CtrlAltDeviant** [jrbudda/minecrift#186] opened 2016-07-10 21:40 UTC
For some reason, my character skin has defaulted back to Steve after installing Vivecraft update 27. I checked it in a single player map and LAN multiplayer session. I tried re-uploading a skin to my profile at Minecraft.net, signed out and back in, but I'm still Steve (it's been over 24 hours). The Minecraft help page says that the skin server is up and running. Am I doing something wrong?

**Comment by Techjar** [comment] 2016-07-13 22:10
I cannot reproduce or explain this. I am sorry.

**Comment by Aesop112** [comment] 2016-07-14 00:50
I also lost my char skin

**Comment by fucnknown** [comment] 2016-07-14 03:51
Encountered this too, fixed by clean install. At this point with all my experiments I keep a copy of the /Roaming/.minecraft folder with a clean slate (after installing Forge), and a copy/backup of mods/shaders/textures/saves, etc.

**Comment by jrbudda** [comment] 2016-07-14 04:10
is this still present in 28r1?

**Comment by CtrlAltDeviant** [comment] 2016-07-23 15:33
Sorry for the late follow up. I just loaded up v29 and I'm still Steve.

**Comment by jrbudda** [comment] 2016-07-29 08:02
this could be a profile issue... maybe try a clean install?

**Closed as completed** 2016-12-01 23:49 UTC
Labels: cannot reproduce
