### ISSUE TITLE
Eye Displacement - Cross-eyed/double vision effect?

### ISSUE THREAD

**Issue by StormComposer** [jrbudda/minecrift#242] opened 2016-10-17 22:26 UTC
Hello! 
I'm having a curious issue with the latest build: the Vive seems to think that your eyes are about a foot or so apart, which leads to menus/text overlapping, subtle weird warping around the edge of the display, and a generally unplayable situation.  You _can_ close either eye to resolve the situation, resulting in a normal, undistorted Minecraft view.  
I'm running it on a GTX 1080 running inside a Razer Core external GPU box, and on a Razer Blade Stealth laptop.  It's a weird setup, but works surprisingly well for VR.

Thanks for making such a nifty mod!  Looking forward to being able to play it. ;)

**Comment by Shadaez** [comment] 2016-10-18 16:25
Same issue here. Left eye feels like it's about a foot or two left of my head

**Comment by Shadaez** [comment] 2016-10-18 16:27
i think this is a duplicate of https://github.com/jrbudda/minecrift/issues/239

**Comment by Shadaez** [comment] 2016-10-18 16:39
see if https://github.com/jrbudda/minecrift/issues/239#issuecomment-254565536 fixes it

**Comment by Techjar** [comment] 2016-10-18 16:40
Yeah, duplicate of #239.

**Closed as completed by Techjar** 2016-10-18 16:40 UTC
Labels: duplicate

**Comment by StormComposer** [comment] 2016-10-19 22:32
AF doesn't seem to have any effect positive or negative (I've had it off the whole time); however, I  have been able to get it to run and function correctly, but the chances of it actually working without the double vision problem are random, about 1 out of every 15 boots will get it to function correctly.  Once you succeed, though, it works fine.  Very weird.

**Comment by Techjar** [comment] 2016-10-19 22:37
Make sure you don't have AF forced on in your NVIDIA control panel, that might also cause the issue.

**Comment by StormComposer** [comment] 2016-10-20 23:09
Nope, it's set to application-specific.  I also tried force-disable, but to the same effect.  It's still a once-in-a-while thing; about 1/8 times you boot it, it'll work, and it'll work indefinitely until you quit.
