### ISSUE TITLE
Fairy lights causes flicking/loading issues

### ISSUE THREAD

**Issue by zeshinumi** [jrbudda/minecrift#139] opened 2016-06-26 21:58 UTC
Trying to load up with the fairy lights mod, there's a lot of flickering going on with the rendered view and some with the in vive view. On top of that, if i try to create or load a world, it just boots me back to the main screen. When I was trying to load this with the SAO-RPG modpack, it broke the main menu entirely (nothing but black/purple textures).

**Comment by zeshinumi** [comment] 2016-06-27 20:55
https://gyazo.com/505748b76ad4dd6a7dae089edccab892 heres a screen capture of the output monitor, this is while its loading up, and it does the same thing even while the room is loaded

**Comment by Techjar** [comment] 2016-06-27 23:49
Errrr, uh... you are using the latest version right? I've seen that mirror flickering thing happen in an older version when "mirror off" mode was broken for a bit.

**Comment by jrbudda** [comment] 2016-06-28 03:11
something is playing with the frame buffers

**Comment by zeshinumi** [comment] 2016-06-28 04:52
Yes, that was the latest version in that screen capture

**Comment by Techjar** [comment] 2016-06-28 04:53
Yeah, that's really weird. Not sure why the mod would be messing with the framebuffers.

**Comment by zeshinumi** [comment] 2016-06-28 11:15
I think they have their source available, I'll take a peak and see if I can find something. What method would I need to look for to see what they are doing to muck with the frame buffer?

**Comment by Techjar** [comment] 2016-06-28 11:29
Can you paste your fml-client-latest.log (gist would be the obvious choice here)? I might know what's really going on here.

**Comment by zeshinumi** [comment] 2016-06-28 11:39
Would that be what's in the launcher while it's running? There's no crash
log

**Comment by zeshinumi** [comment] 2016-06-28 11:41
Ah XD shoulda went here instead of replying to email. I'll get it soon as I get home from work

**Comment by zeshinumi** [comment] 2016-06-28 23:15
here's the pastbin of the fml-client-latest.log
http://pastebin.com/jJn3d8LK

**Comment by Techjar** [comment] 2016-06-29 05:13
Hmm, so the flickering is happening if something throws an exception during initialization. The mod is crashing due to this: java.lang.NoSuchFieldException: currentFrustum

**Comment by Techjar** [comment] 2016-06-29 05:23
He's ASMing into the EntityRenderer, adding a field called "currentFrustum" and trying to change the part that instantiates the frustum to assign to that field. I doubt it will work, but try this build:

[vivecraft-1.7.10-Vivecraft-jrbudda24-test2-installer.exe](https://owncloud.techjargaming.com/index.php/s/WAdTKj7ZxncCooi/download)

**Comment by zeshinumi** [comment] 2016-06-29 06:48
looks like it runs, although all the fairy lights don't render. A step in a right direction though :D

**Comment by Techjar** [comment] 2016-06-29 07:41
Er... it actually renders just fine for me.
![image](https://qimg.techjargaming.com/i/ZYKfXH7Z.png)

**Comment by Techjar** [comment] 2016-06-29 07:42
Let's mark this fixed and if you can't solve the render issue which I can't reproduce, make a separate issue.

**Closed as completed by Techjar** 2016-06-29 07:42 UTC
Labels: mod bug
