### ISSUE TITLE
HUD is the entire screen, as opposed to just the hotbar

### ISSUE THREAD

**Issue by aciou** [jrbudda/minecrift#195] opened 2016-07-25 08:56 UTC
![bug](https://cloud.githubusercontent.com/assets/20638467/17095716/4e2c430a-5299-11e6-9f24-7d0fcf7f6caa.png)

I didn't have this issue with 1.7. Couldn't fix it in HUD settings.

**Comment by jrbudda** [comment] 2016-07-25 14:53
do a reset of the video options. It's one of them. I haven't figured out which.

**Comment by aciou** [comment] 2016-07-26 04:24
No worries, I'll give that a go. Thanks for all your work.

**Comment by jrbudda** [comment] 2016-07-28 04:22
duplicate of https://github.com/jrbudda/Vivecraft_110/issues/19

closing here.

**Closed as completed by jrbudda** 2016-07-28 04:22 UTC
Labels: bug, 1.10
